# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  notify_success:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: ${{ needs.deploy.result == 'success' }}
    steps: 
      - name: Notify discord
        uses: rjstone/discord-webhook-notify@v2
        with: 
          - webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          - usermane: Discord bot
          - severity: info
          - title: Build & Deployment Successfull
          - description: Commit [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) deployed successfully

  notify_failure:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: ${{ needs.deploy.result == 'failure ' }}
    steps: 
      - name: Notify discord
        uses: rjstone/discord-webhook-notify@v2
        with: 
          - webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          - usermane: Discord bot
          - severity: error
          - title: Deployment Error
          - description: Deployment failed for commit [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
