name: periodic_health_check

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Healt Check 
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.APP_URL }}
          max-attempts: 3
          retry-delay: 5s

